const REPO = 'ilyaminineli/oleg_ustinov_official';
const BRANCH = 'main';
const TREE_URL = `https://api.github.com/repos/${REPO}/git/trees/${BRANCH}?recursive=1`;
const RAW_ROOT = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/`;
const archiveRoot = document.getElementById('works-archive');
const yearRow = document.getElementById('year-row');
const filterRow = document.getElementById('filter-row');
const status = document.getElementById('archive-status');
const conceptionList = document.getElementById('conception-list');
const seriesModal = document.getElementById('series-modal');
const seriesModalContent = document.getElementById('series-modal-content');
const lightbox = document.getElementById('lightbox');
const lightboxImage = document.getElementById('lightbox-image');
const lightboxCaption = document.getElementById('lightbox-caption');
let artworks = []; let conceptions = []; let activeYear = 'all'; let activeTags = []; let sortMode = 'year';
const titleTranslations = { 'Серия Caustic Window': 'Caustic Window', 'Серия IDM': 'IDM', 'Серия графики': 'Graphics', 'Серия Сошествие': 'Descent', 'Серия работ в Сфере': 'Works in the Sphere', 'Серия UUuUU': 'UUuUU', 'Серия Silent Mode (плохое качество)': 'Silent Mode', 'Дорожные происшествия (совместно с Иваном Горшковым)': 'Road Accidents', 'Львиный Хребет': 'Lion’s Spine', 'Львиный хребет 2020': 'Lion’s Spine', 'Без названия': 'Untitled' };
const mediaTranslations = [[/\bхолст\b/gi, 'canvas'], [/\bакрил\b/gi, 'acrylic'], [/\bспрей\b/gi, 'spray paint'], [/\bмаркер\b/gi, 'marker'], [/многократная печать/gi, 'multilayer printing'], [/смешанная техника/gi, 'mixed media'], [/\bкартон\b/gi, 'cardboard'], [/\bмасло\b/gi, 'oil'], [/\bдсп\b/gi, 'hardboard'], [/\bфанера\b/gi, 'plywood'], [/\bбумага\b/gi, 'paper'], [/\bкарандаш\b/gi, 'pencil'], [/\bпастель\b/gi, 'pastel'], [/\bштукатурка\b/gi, 'plaster'], [/\bколлаж\b/gi, 'collage'], [/детал[ьи]/gi, 'details']];
function safeHtml(value = '') { return String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function pathUrl(path) { return RAW_ROOT + path.split('/').map(encodeURIComponent).join('/'); }
function githubFileUrl(path) { return `https://github.com/${REPO}/blob/${BRANCH}/${path.split('/').map(encodeURIComponent).join('/')}`; }
function normalize(text) { return String(text).toLowerCase().replace(/[“”"'’]/g, '').replace(/[()\[\]{}]/g, ' ').replace(/\bсерия\b|\bконцепция\b|\bconcept\b|\bconception\b|\(\+concept\)/gi, ' ').replace(/[^a-z0-9а-яё]+/gi, ' ').replace(/\s+/g, ' ').trim(); }
function englishText(text = '') { let out = String(text); mediaTranslations.forEach(([re, v]) => out = out.replace(re, v)); return titleTranslations[out] || out; }
function firstYear(text) { const m = String(text).match(/\b(?:19|20)\d{2}\b/); return m ? Number(m[0]) : 9999; }
function displaySeries(series) { let s = englishText(series || 'Independent works'); return s.replace(/^Series\s+/i, '').replace(/\s*\(\+concept\)/i, '').replace(/\s*\(\+conception\)/i, '') || 'Independent works'; }
function matchSeriesMeta(series) { const n = normalize(series); return Object.entries(typeof SERIES_META === 'object' ? SERIES_META : {}).find(([key]) => normalize(key) === n)?.[1] || null; }
function matchConcept(series) { const n = normalize(series || ''); return conceptions.find(c => normalize(c.folder) === n) || null; }
function parseArtwork(entry) {
  const parts = entry.path.split('/'), filename = parts[parts.length - 1], basename = filename.replace(/\.[^.]+$/, '');
  const bits = basename.split(',').map(v => v.trim()).filter(Boolean), yearIndex = bits.findIndex(v => /(?:19|20)\d{2}/.test(v));
  const rawYear = yearIndex >= 0 ? bits[yearIndex] : (parts[1] || ''), metadata = yearIndex >= 0 ? bits.slice(yearIndex + 1).join(', ') : '';
  const folderSeries = parts.length >= 4 ? parts[2] : ''; const lower = `${basename} ${metadata} ${folderSeries}`.toLowerCase();
  const detail = /\bdetail\b|details|деталь|детали/i.test(lower), installation = /installation view|interior view/i.test(lower); const tags = new Set();
  if (/mixed media|mixed technique|смешан/.test(lower)) tags.add('mixed-media'); if (/\bprint\b|printing|многократная печать/.test(lower)) tags.add('print'); if (/canvas|холст/.test(lower)) tags.add('canvas'); if (/paper|бумаг|картон/.test(lower)) tags.add(/картон/.test(lower) ? 'cardboard' : 'paper'); if (/hardboard|дсп/.test(lower)) tags.add('hardboard'); if (/plywood|фанер/.test(lower)) tags.add('plywood'); if (/banner/.test(lower)) tags.add('banner'); if (/collage|коллаж/.test(lower)) tags.add('collage'); if (/reflective film/.test(lower)) tags.add('reflective-film'); if (/acrylic|oil|spray|aerosol|marker|latex|pastel|pencil|pen|ink|enamel|акрил|масло|спрей|маркер/.test(lower)) tags.add('painting'); if (detail) tags.add('detail'); if (installation) tags.add('installation'); if (/in progress|плохое качество|unfinished|не закон/.test(lower)) tags.add('in-progress');
  const meta = matchSeriesMeta(folderSeries); if (meta?.tags) meta.tags.forEach(t => tags.add(t));
  const titleBits = yearIndex > 0 ? bits.slice(0, yearIndex).join(', ') : basename;
  return { path: entry.path, title: englishText(titleBits), year: rawYear, sortYear: firstYear(rawYear), metadata: englishText(metadata), series: englishText(folderSeries), tags: [...tags], detail, installation };
}
function renderFilters() {
  const years = [...new Set(artworks.map(w => String(w.sortYear)).filter(y => y !== '9999'))].sort((a, b) => Number(b) - Number(a));
  if (yearRow) yearRow.innerHTML = [`<button class="tag ${activeYear === 'all' ? 'active' : ''}" data-year="all">#all</button>`, ...years.map(y => `<button class="tag ${activeYear === y ? 'active' : ''}" data-year="${y}">#${y}</button>`)].join('');
  const metaTags = Object.values(typeof SERIES_META === 'object' ? SERIES_META : {}).flatMap(m => m.tags || []); const tags = [...new Set([...artworks.flatMap(w => w.tags), ...metaTags].filter(t => !['detail', 'installation'].includes(t)))].sort();
  if (filterRow) filterRow.innerHTML = [...tags.map(t => `<button class="tag ${activeTags.includes(t) ? 'active' : ''}" data-tag="${safeHtml(t)}">#${safeHtml(t)}</button>`), `<button class="tag clear-tags ${activeTags.length ? 'visible' : ''}" data-clear-tags>clear</button>`].join('');
}
function filteredArtworks() { return artworks.filter(w => (activeYear === 'all' || String(w.sortYear) === activeYear) && (activeTags.length === 0 || activeTags.every(tag => w.tags.includes(tag)))); }
function sortWorks(list) { return [...list].sort((a, b) => sortMode === 'medium' ? a.metadata.localeCompare(b.metadata) || a.title.localeCompare(b.title) : b.sortYear - a.sortYear || a.title.localeCompare(b.title)); }
function seriesGroups() { const groups = new Map(); sortWorks(filteredArtworks()).forEach(w => { const key = `${w.year}|||${w.series || 'Independent works'}`; if (!groups.has(key)) groups.set(key, { year: w.year, series: w.series, works: [] }); groups.get(key).works.push(w); }); return [...groups.values()]; }
function seriesPreview(group) { const mains = group.works.filter(w => !w.detail), details = group.works.filter(w => w.detail), shots = [...mains.slice(0, 2), ...details.slice(0, 1)].slice(0, 3); return `<div class="series-preview-grid">${shots.map(w => `<div class="series-preview-shot ${w.detail ? 'detail-shot' : ''}"><img src="${pathUrl(w.path)}" alt="${safeHtml(w.title)}" loading="lazy">${w.detail ? '<span class="preview-label">detail</span>' : ''}</div>`).join('')}</div>`; }
function renderArchive() {
  if (!archiveRoot) return; const groups = seriesGroups(), byYear = new Map(); groups.forEach(g => { const y = g.year || 'Archive'; if (!byYear.has(y)) byYear.set(y, []); byYear.get(y).push(g); });
  archiveRoot.innerHTML = [...byYear.entries()].map(([year, items]) => `<section class="year-section"><div class="year-heading"><span class="year-big">${safeHtml(year)}</span><span>${items.length} series</span></div><div class="series-grid">${items.map(g => { const info = matchSeriesMeta(g.series), concept = matchConcept(g.series), details = g.works.filter(w => w.detail).length; const tags = [...(info?.tags || []), ...g.works.flatMap(w => w.tags)].filter((v, i, a) => v && a.indexOf(v) === i && v !== 'detail' && v !== 'installation'); return `<article class="series-card" data-series-key="${safeHtml(g.year + '|||' + (g.series || 'Independent works'))}">${seriesPreview(g)}<div class="series-card-info"><div class="series-card-top"><div><p class="eyebrow">${safeHtml(g.year || 'archive')}</p><h2>${safeHtml(displaySeries(g.series))}</h2></div><span class="series-count">${g.works.length} works</span></div><div class="series-tags">${tags.slice(0, 10).map(t => `<button class="tag static-tag series-filter-tag" data-tag="${safeHtml(t)}">#${safeHtml(t)}</button>`).join('')}</div><div class="series-foot"><span>${details ? `${details} details` : ''}</span><span>${concept || info?.concept ? 'concept ↗' : ''}</span></div></div></article>`; }).join('')}</div></section>`).join('') || '<div class="archive-empty">No works match this filter.</div>';
}
function conceptMarkup(concept) { if (!concept) return ''; const file = concept.files.find(f => /\.docx$/i.test(f.name)); if (!file) return ''; return `<section class="series-conception"><div class="section-heading"><p class="eyebrow">text</p><h2>conception</h2></div><div class="concept-actions"><span>embedded document</span><a class="conception-link-inline" href="${githubFileUrl(file.path)}" target="_blank" rel="noreferrer">source ↗</a></div><div class="concept-preview" data-concept-preview><span>loading text…</span></div></section>`; }
function renderWorkCard(w) { return `<article class="series-work" data-image="${safeHtml(w.path)}"><div class="series-work-image"><img src="${pathUrl(w.path)}" alt="${safeHtml(w.title)}" loading="lazy"></div><div class="series-work-meta"><strong>${safeHtml(w.title)}</strong><span>${safeHtml(w.year)}</span><span>${safeHtml(w.metadata)}</span><div class="work-tags">${w.tags.filter(t => !['detail', 'installation'].includes(t)).map(t => `<span class="tag static-tag">#${safeHtml(t)}</span>`).join('')}</div></div></article>`; }
async function renderDocx(path, container) { if (!container || !path) return; container.innerHTML = '<span>loading text…</span>'; try { if (typeof docx === 'undefined') throw new Error('docx renderer unavailable'); const response = await fetch(pathUrl(path)); if (!response.ok) throw new Error(`document ${response.status}`); const blob = await response.blob(); container.innerHTML = ''; await docx.renderAsync(blob, container, null, { className: 'docx-content', inWrapper: false, breakPages: false, ignoreWidth: false }); } catch (error) { console.error(error); container.innerHTML = `<div class="concept-error">Could not render this document here. <a href="${githubFileUrl(path)}" target="_blank" rel="noreferrer">Open the source document ↗</a></div>`; } }
function openConcept(path, title = 'Conception') { if (!seriesModal || !seriesModalContent) return; seriesModalContent.innerHTML = `<div class="series-modal-head"><div><p class="eyebrow">text</p><h1>${safeHtml(title)}</h1></div><div class="series-modal-stats"><span>document</span></div></div><section class="concept-reader"><div class="concept-reader-bar"><span>conception</span><a href="${githubFileUrl(path)}" target="_blank" rel="noreferrer">source ↗</a></div><div class="concept-reader-body" data-concept-reader>loading text…</div></section>`; seriesModal.classList.add('open'); seriesModal.setAttribute('aria-hidden', 'false'); document.body.classList.add('modal-open'); renderDocx(path, seriesModalContent.querySelector('[data-concept-reader]')); }
function openSeries(key) {
  const [year, seriesName] = key.split('|||'), group = seriesGroups().find(g => g.year === year && (g.series || 'Independent works') === seriesName); if (!group || !seriesModal) return;
  const info = matchSeriesMeta(group.series), concept = matchConcept(group.series), mains = group.works.filter(w => !w.detail), details = group.works.filter(w => w.detail);
  seriesModalContent.innerHTML = `<div class="series-modal-head"><div><p class="eyebrow">${safeHtml(year)}</p><h1>${safeHtml(displaySeries(group.series))}</h1></div><div class="series-modal-stats"><span>${mains.length} works</span><span>${details.length} details</span>${concept || info?.concept ? '<span>concept</span>' : ''}</div></div>${conceptMarkup(concept)}${mains.length ? `<section class="series-modal-section"><div class="section-heading"><p class="eyebrow">works</p><h2>main works</h2></div><div class="series-work-grid">${mains.map(renderWorkCard).join('')}</div></section>` : ''}${details.length ? `<section class="series-modal-section"><div class="section-heading"><p class="eyebrow">details</p><h2>details / close-ups</h2></div><div class="detail-scroll">${details.map(renderWorkCard).join('')}</div></section>` : ''}`;
  seriesModal.classList.add('open'); seriesModal.setAttribute('aria-hidden', 'false'); document.body.classList.add('modal-open');
  const preview = seriesModalContent.querySelector('[data-concept-preview]'); const conceptFile = concept?.files.find(f => /\.docx$/i.test(f.name)); if (preview && conceptFile) renderDocx(conceptFile.path, preview);
}
function closeSeries() { seriesModal?.classList.remove('open'); seriesModal?.setAttribute('aria-hidden', 'true'); document.body.classList.remove('modal-open'); }
function renderConceptions() { if (!conceptionList) return; if (!conceptions.length) { conceptionList.innerHTML = '<p class="projects-empty">No conception texts found.</p>'; return; } conceptionList.innerHTML = conceptions.map(c => { const file = c.files.find(f => /\.docx$/i.test(f.name)); return `<article class="conception-card"><div><p class="eyebrow">concept</p><h3>${safeHtml(displaySeries(c.folder))}</h3></div><div class="conception-files">${file ? `<button class="conception-open-list" data-concept-path="${safeHtml(file.path)}" data-concept-title="${safeHtml(displaySeries(c.folder))}">read on site ↗</button>` : `${c.files.map(f => `<a class="conception-link" href="${githubFileUrl(f.path)}" target="_blank" rel="noreferrer"><span>${safeHtml(f.name.replace(/\.[^.]+$/, ''))}</span><span>↗</span></a>`).join('')}`}</div></article>`; }).join(''); }
async function loadArchive() {
  try {
    const response = await fetch(TREE_URL, { headers: { Accept: 'application/vnd.github+json' } }); if (!response.ok) throw new Error(`GitHub API ${response.status}`); const data = await response.json();
    artworks = (data.tree || []).filter(i => i.type === 'blob' && i.path.startsWith('img/') && !/tags_n_meta\.ods$/i.test(i.path) && /\.(jpe?g|png|webp|gif)$/i.test(i.path)).map(parseArtwork);
    const conceptMap = new Map(); (data.tree || []).filter(i => i.type === 'blob' && i.path.startsWith('txt/') && !/text_files\.md$/i.test(i.path)).forEach(i => { const p = i.path.split('/'); if (p.length < 3) return; const folder = p[1]; if (!conceptMap.has(folder)) conceptMap.set(folder, { folder, files: [] }); conceptMap.get(folder).files.push({ name: p[p.length - 1], path: i.path }); });
    conceptions = [...conceptMap.values()].filter(c => c.files.length); renderFilters(); renderArchive(); renderConceptions(); if (status) status.textContent = `${artworks.length} images · ${new Set(artworks.map(w => w.series).filter(Boolean)).size} series · ${conceptions.length} conception groups`;
  } catch (error) { console.error(error); if (status) status.textContent = 'Archive could not be loaded automatically.'; if (archiveRoot) archiveRoot.innerHTML = '<div class="archive-empty">The archive is temporarily unavailable. Please reload the page.</div>'; }
}
document.addEventListener('click', event => { const year = event.target.closest('[data-year]'), tag = event.target.closest('[data-tag]'), clear = event.target.closest('[data-clear-tags]'), sort = event.target.closest('[data-sort]'), seriesWork = event.target.closest('.series-work'), conceptListButton = event.target.closest('.conception-open-list'), seriesCard = event.target.closest('.series-card'); if (year) { activeYear = year.dataset.year; renderFilters(); renderArchive(); return; } if (tag) { const value = tag.dataset.tag; activeTags = activeTags.includes(value) ? activeTags.filter(t => t !== value) : [...activeTags, value]; renderFilters(); renderArchive(); return; } if (clear) { activeTags = []; renderFilters(); renderArchive(); return; } if (sort) { sortMode = sort.dataset.sort; document.querySelectorAll('[data-sort]').forEach(b => b.classList.toggle('active', b.dataset.sort === sortMode)); renderArchive(); return; } if (conceptListButton) { openConcept(conceptListButton.dataset.conceptPath, conceptListButton.dataset.conceptTitle || 'Conception'); return; } if (seriesWork) { lightboxImage.src = pathUrl(seriesWork.dataset.image); lightboxImage.alt = seriesWork.querySelector('strong')?.textContent || ''; lightboxCaption.textContent = seriesWork.querySelector('.series-work-meta')?.innerText || ''; lightbox.classList.add('open'); lightbox.setAttribute('aria-hidden', 'false'); return; } if (seriesCard) { openSeries(seriesCard.dataset.seriesKey); return; } });
document.getElementById('series-close')?.addEventListener('click', closeSeries); seriesModal?.addEventListener('click', event => { if (event.target === seriesModal) closeSeries(); }); document.getElementById('lightbox-close')?.addEventListener('click', () => { lightbox.classList.remove('open'); lightbox.setAttribute('aria-hidden', 'true'); }); lightbox?.addEventListener('click', event => { if (event.target === lightbox) { lightbox.classList.remove('open'); lightbox.setAttribute('aria-hidden', 'true'); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { if (lightbox?.classList.contains('open')) { lightbox.classList.remove('open'); lightbox.setAttribute('aria-hidden', 'true'); } else closeSeries(); } }); loadArchive();